pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'LuaTweaker'

include 'common-api'
include 'core-engine'
include 'modules:module-recipes'
include 'modules:module-content'
include 'modules:module-entities'
include 'modules:module-interaction'
include 'modules:module-events'
include 'modules:module-math'
include 'modules:module-storage'
include 'modules:module-network'
include 'modules:module-client'
include 'modules:module-interception'
include 'modules:module-command'
include 'modules:module-tasks'
include 'neoforge-platform'
