package com.luatweaker.api.dimension;

import com.luatweaker.api.annotation.LuaDoc;
import com.luatweaker.api.entity.IEntity;
import com.luatweaker.api.vm.ILuaValue;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Service for creating and managing custom dimensions.
 *
 * <p>Dimensions are configured in Lua with {@code Dimensions.Create(...)} and
 * materialized on the platform side as datapack dimension type + dimension
 * entries whose terrain/biome are generated by Lua callbacks.</p>
 */
@LuaDoc(description = "Service for creating and managing custom dimensions with Lua terrain generation.")
public interface IDimensionService {

    @LuaDoc(
        description = "Register a new dimension from a config table (hasSkyLight, seaLevel, surfaceBlock, biomes, features, spawnEntities, ...).",
        params = {"dimensionId: string - e.g. 'arcane:crystal_realm'",
                  "config: table - dimension config (terrain, blocks, biomes, visuals, spawn)"},
        returnType = "void"
    )
    void create(@NotNull String dimensionId, @NotNull ILuaValue config);

    @LuaDoc(
        description = "Set the terrain generator callback. The function receives (x, z, baseHeight) and returns (height, blockId).",
        params = {"dimensionId: string", "luaFunction: function - function(x, z, baseHeight) -> height, blockId"},
        returnType = "void"
    )
    void setTerrainGenerator(@NotNull String dimensionId, @NotNull Object luaFunction);

    @LuaDoc(
        description = "Set the biome provider callback. The function receives (x, z) and returns a biome id string (e.g. 'arcane:crystal_plains').",
        params = {"dimensionId: string", "luaFunction: function - function(x, z) -> biomeId"},
        returnType = "void"
    )
    void setBiomeProvider(@NotNull String dimensionId, @NotNull Object luaFunction);

    @LuaDoc(
        description = "Low-level block picker: overrides the default column fill. The function receives (x, z, surfaceY, minY) and returns a table {[y] = blockId, ...} - use 'minecraft:air' to carve caves.",
        params = {"dimensionId: string",
                  "luaFunction: function - function(x, z, surfaceY, minY) -> {[y] = blockId, ...}"},
        returnType = "void"
    )
    void setBlockPicker(@NotNull String dimensionId, @NotNull Object luaFunction);

    @LuaDoc(
        description = "Custom strata picker: overrides the ground layers per column. The function receives (x, z, surfaceY) and returns a table {[depthFromSurface] = blockId, ...} (depth 1 = the block below the surface).",
        params = {"dimensionId: string",
                  "luaFunction: function - function(x, z, surfaceY) -> {[depth] = blockId, ...}"},
        returnType = "void"
    )
    void setStrataPicker(@NotNull String dimensionId, @NotNull Object luaFunction);

    @LuaDoc(
        description = "Set a custom spawn position for the dimension (used by teleports).",
        params = {"dimensionId: string", "x: number", "z: number"},
        returnType = "void"
    )
    void setSpawnPoint(@NotNull String dimensionId, int x, int z);

    @LuaDoc(
        description = "Get the dimension a portal block leads to, or nil.",
        params = {"blockId: string"},
        returnType = "string|nil"
    )
    @Nullable
    String getPortalTarget(@NotNull String blockId);

    @LuaDoc(
        description = "Register a portal block that leads to the target dimension. The mapping is exposed via getDimension().portals.",
        params = {"blockId: string - e.g. 'arcane:crystal_portal'", "targetDimension: string"},
        returnType = "void"
    )
    void registerPortal(@NotNull String blockId, @NotNull String targetDimension);

    @LuaDoc(
        description = "Teleport a player to the given dimension (at a safe surface position).",
        params = {"player: Player - player entity table", "dimensionId: string"},
        returnType = "void"
    )
    void teleportTo(@NotNull IEntity player, @NotNull String dimensionId);

    @LuaDoc(
        description = "Get dimension info as a table (id, terrain, blocks, biomes, features, spawnEntities, portals) or nil if unknown.",
        params = {"dimensionId: string"},
        returnType = "table|nil"
    )
    @Nullable
    Object getDimension(@NotNull String dimensionId);
}
