package com.luatweaker.platform.content;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.luatweaker.api.content.BooleanStateSpec;
import com.luatweaker.api.content.IDatapackService;

/**
 * Generates blockstate/model JSONs for Lua-configured block variants entirely in
 * memory (zero hand-written JSON):
 *
 * <ul>
 *   <li><b>boolean state</b> ({@code :BooleanState("running", offTex, onTex)}) —
 *       blockstate with the two variants plus two cube-all models;</li>
 *   <li><b>pipe connections</b> ({@code :ConnectionState(true)}) — blockstate for
 *       all 64 north/east/south/west/up/down combinations plus one pipe model per
 *       combination (center block + arms), textured with the block texture.</li>
 * </ul>
 *
 * Files are written into the virtual pack through {@link IDatapackService}, so
 * they survive reloads (regenerated by {@link LuaAssetsPackFinder#rebuildVirtualFiles()}).
 */
public final class MachineAssetGenerator {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private static final int[] DIR_X = {5, 11, 5, 5, 5, 5};
    private static final int[] DIR_Y = {5, 5, 5, 5, 11, 0};
    private static final int[] DIR_Z = {0, 5, 11, 5, 5, 5};
    private static final int[] DIR_TX = {11, 16, 11, 5, 11, 11};
    private static final int[] DIR_TY = {11, 11, 11, 11, 16, 5};
    private static final int[] DIR_TZ = {5, 11, 16, 11, 11, 11};
    private static final String[] CONNECTION_NAMES = {"north", "east", "south", "west", "up", "down"};
    /** 6 boolean connection properties -> 2^6 = 64 combinations. */
    private static final int CONNECTION_COMBOS = 1 << 6;

    private MachineAssetGenerator() {}

    /**
     * Generates all variant assets for a block builder (boolean state + pipe
     * connections). Both features may coexist: the pipe model then serves all
     * state values, and the blockstate maps every combination.
     *
     * @param datapack target virtual pack (never null at runtime)
     * @param ns       block namespace (e.g. "luatweaker")
     * @param id       block path (e.g. "ruby_charger")
     * @param state    boolean-state pair, null = none
     * @param connections whether pipe connection properties are enabled
     * @param texture  pipe texture (block texture or the default ns:block/id)
     */
    public static void generate(IDatapackService datapack, String ns, String id,
                                BooleanStateSpec state, boolean connections, String texture) {
        if (datapack == null) return;
        if (state != null && !connections) {
            generateBooleanState(datapack, ns, id, state);
        } else if (connections) {
            generatePipe(datapack, ns, id, state, texture);
        }
    }

    private static void generateBooleanState(IDatapackService datapack, String ns, String id, BooleanStateSpec state) {
        String prop = state.property();
        JsonObject variants = new JsonObject();
        variants.add(prop + "=false", variantModel(ns + ":block/" + id));
        variants.add(prop + "=true", variantModel(ns + ":block/" + id + "_" + prop));
        datapack.addData("assets/" + ns + "/blockstates/" + id + ".json", blockstate(variants));
        datapack.addData("assets/" + ns + "/models/block/" + id + ".json", cubeAll(state.offTexture()));
        datapack.addData("assets/" + ns + "/models/block/" + id + "_" + prop + ".json", cubeAll(state.onTexture()));
        datapack.addData("assets/" + ns + "/models/item/" + id + ".json", parentModel(ns + ":block/" + id));
    }

    private static void generatePipe(IDatapackService datapack, String ns, String id,
                                     BooleanStateSpec state, String texture) {
        String tex = texture != null && !texture.isBlank() ? texture : ns + ":block/" + id;
        String modelPrefix = ns + ":block/" + id + "_pipe_";
        boolean hasState = state != null;

        JsonObject variants = new JsonObject();
        int stateValues = hasState ? 2 : 1;
        for (int sv = 0; sv < stateValues; sv++) {
            for (int combo = 0; combo < CONNECTION_COMBOS; combo++) {
                String connKey = connectionKey(combo);
                String stateKey = hasState ? state.property() + "=" + (sv == 0) + "," + connKey : connKey;
                variants.add(stateKey, variantModel(modelPrefix + comboName(combo)));
            }
        }
        datapack.addData("assets/" + ns + "/blockstates/" + id + ".json", blockstate(variants));

        for (int combo = 0; combo < CONNECTION_COMBOS; combo++) {
            datapack.addData("assets/" + ns + "/models/block/" + id + "_pipe_" + comboName(combo) + ".json",
                    pipeModel(tex, combo));
        }

        datapack.addData("assets/" + ns + "/models/item/" + id + ".json",
                parentModel(modelPrefix + "000000"));
    }

    private static String connectionKey(int combo) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 6; i++) {
            if (i > 0) sb.append(',');
            sb.append(CONNECTION_NAMES[i]).append('=').append((combo & (1 << i)) != 0);
        }
        return sb.toString();
    }

    private static String comboName(int combo) {
        StringBuilder sb = new StringBuilder(6);
        for (int i = 0; i < 6; i++) {
            sb.append((combo & (1 << i)) != 0 ? '1' : '0');
        }
        return sb.toString();
    }

    private static String blockstate(JsonObject variants) {
        JsonObject bs = new JsonObject();
        bs.add("variants", variants);
        return GSON.toJson(bs);
    }

    private static JsonObject variantModel(String model) {
        JsonObject v = new JsonObject();
        v.addProperty("model", model);
        return v;
    }

    private static String cubeAll(String texture) {
        return "{\n  \"parent\": \"minecraft:block/cube_all\",\n  \"textures\": {\n    \"all\": \""
                + texture + "\"\n  }\n}";
    }

    private static String parentModel(String parent) {
        return "{\n  \"parent\": \"" + parent + "\"\n}";
    }

    /** Center cube (6x6x6) plus one arm per connected direction, uv-projected per face. */
    private static String pipeModel(String texture, int combo) {
        JsonObject model = new JsonObject();
        model.addProperty("parent", "block/block");
        JsonObject textures = new JsonObject();
        textures.addProperty("particle", texture);
        textures.addProperty("pipe", texture);
        model.add("textures", textures);

        JsonArray elements = new JsonArray();
        elements.add(cubeElement(5, 5, 5, 11, 11, 11));
        for (int i = 0; i < 6; i++) {
            if ((combo & (1 << i)) != 0) {
                elements.add(cubeElement(DIR_X[i], DIR_Y[i], DIR_Z[i], DIR_TX[i], DIR_TY[i], DIR_TZ[i]));
            }
        }
        model.add("elements", elements);
        return GSON.toJson(model);
    }

    private static JsonObject cubeElement(int fx, int fy, int fz, int tx, int ty, int tz) {
        JsonObject el = new JsonObject();
        el.add("from", array(fx, fy, fz));
        el.add("to", array(tx, ty, tz));
        JsonObject faces = new JsonObject();
        faces.add("north", face(fx, fy, tx, ty));
        faces.add("south", face(fx, fy, tx, ty));
        faces.add("west", face(fz, fy, tz, ty));
        faces.add("east", face(fz, fy, tz, ty));
        faces.add("up", face(fx, fz, tx, tz));
        faces.add("down", face(fx, fz, tx, tz));
        el.add("faces", faces);
        return el;
    }

    private static JsonObject face(int u1, int v1, int u2, int v2) {
        JsonObject f = new JsonObject();
        f.add("uv", array(u1, v1, u2, v2));
        f.addProperty("texture", "#pipe");
        return f;
    }

    private static JsonArray array(int... values) {
        JsonArray arr = new JsonArray();
        for (int value : values) {
            arr.add(value);
        }
        return arr;
    }
}
