-- ================================================================
-- ARCANE RPG: Content Registration
-- Items, Blocks, Entity Types, Creative Tabs
-- ================================================================
local Content = require("LuaTweaker.Content")
local Constants = 
-- ==== CREATIVE TAB ====
Content.createTab("arcane_tab", function(tab)
    tab:title("Arcane RPG")
       :icon("luatweaker:crystal_shard")
end)

-- ==== ITEMS ====

local CrystalShard = Content.NewItem("crystal_shard")
    :MaxStackSize(64)
    :Rarity("UNCOMMON")
    :DisplayName("Arcane Crystal Shard")
    :CreativeTab("arcane_tab")
    :Tag("c:gems/crystal")
    :Glow(true)
    :Tooltip("§bPulses with arcane energy")
    :Register()

local CrystalStaff = Content.NewItem("crystal_staff")
    :MaxStackSize(1)
    :Rarity("EPIC")
    :Durability(500)
    :DisplayName("Crystal Staff")
    :CreativeTab("arcane_tab")
    :Glow(true)
    :Tooltip("§bChannel the arcane through this crystalline focus")
    :Tooltip("§7Right-click to cast Crystal Bolt")
    :OnRightClick(function(player, itemStack)
        local Events = require("LuaTweaker.Events")
        Events:Fire("ArcaneCastSkill", { player = player, skill = "crystal_bolt" })
    end)
    :Register()

local CrystalSword = Content.NewItem("crystal_sword")
    :Rarity("RARE")
    :Durability(800)
    :AttackDamage(9.0)
    :AttackSpeed(1.6)
    :DisplayName("Crystal Blade")
    :CreativeTab("arcane_tab")
    :Tooltip("§bA blade forged from pure crystal")
    :OnHitEntity(function(target, attacker)
        local swordCfg = mod and mod:GetConfig() or {}
        local slowChance = tonumber(swordCfg.crystal_sword_slow_chance) or 0.15
        local slowTicks = tonumber(swordCfg.crystal_sword_slow_ticks) or 40
        if math.random() < slowChance then
            target:addEffect("slowness", slowTicks, 1)
            attacker:sendActionBar("§bCrystal frost enchants your blade!")
        end
    end)
    :Register()

Content.createArmorMaterial("crystal", function(mat)
    mat:layer("luatweaker:crystal")
       :equipSound("minecraft:item.armor.equip_diamond")
       :toughness(1.5)
       :knockbackResistance(0.05)
       :enchantability(20)
       :defense("helmet", 3)
       :defense("chestplate", 8)
       :defense("leggings", 6)
       :defense("boots", 3)
end)

local CrystalHelmet = Content.NewItem("crystal_helmet")
    :Type("helmet")
    :Rarity("RARE")
    :Durability(600)
    :Defense(3)
    :Toughness(1.5)
    :ArmorMaterial("crystal")
    :ArmorTexture("luatweaker:crystal")
    :DisplayName("Crystal Helm")
    :CreativeTab("arcane_tab")
    :Register()

local CrystalChestplate = Content.NewItem("crystal_chestplate")
    :Type("chestplate")
    :Rarity("RARE")
    :Durability(700)
    :Defense(8)
    :Toughness(2.0)
    :ArmorMaterial("crystal")
    :ArmorTexture("luatweaker:crystal")
    :DisplayName("Crystal Cuirass")
    :CreativeTab("arcane_tab")
    :Register()

local CrystalLeggings = Content.NewItem("crystal_leggings")
    :Type("leggings")
    :Rarity("RARE")
    :Durability(650)
    :Defense(6)
    :Toughness(1.5)
    :ArmorMaterial("crystal")
    :ArmorTexture("luatweaker:crystal")
    :DisplayName("Crystal Legguards")
    :CreativeTab("arcane_tab")
    :Register()

local CrystalBoots = Content.NewItem("crystal_boots")
    :Type("boots")
    :Rarity("RARE")
    :Durability(550)
    :Defense(3)
    :Toughness(1.0)
    :ArmorMaterial("crystal")
    :ArmorTexture("luatweaker:crystal")
    :DisplayName("Crystal Boots")
    :CreativeTab("arcane_tab")
    :Register()

local ManaPotion = Content.NewItem("mana_potion")
    :MaxStackSize(16)
    :Rarity("UNCOMMON")
    :DisplayName("Mana Potion")
    :CreativeTab("arcane_tab")
    :Food(0, 0)
    :AlwaysEdible()
    :Tooltip("§9Restores 50 mana instantly")
    :OnConsume(function(player, stack)
        local ManaSystem = require(".src.server.mana_system")
        local potionCfg = mod and mod:GetConfig() or {}
        local restore = tonumber(potionCfg.mana and potionCfg.mana.potion_restore) or 50
        ManaSystem:RestoreMana(player, restore)
        player:sendActionBar("§9+" .. tostring(restore) .. " Mana restored!")
        player:playSound("minecraft:item.honey_bottle.drink", 1.0, 1.5)
    end)
    :Register()

local SpellTome = Content.NewItem("spell_tome")
    :MaxStackSize(1)
    :Rarity("EPIC")
    :DisplayName("Tome of Meteor Strike")
    :CreativeTab("arcane_tab")
    :Glow(true)
    :Tooltip("§dTeaches the ultimate arcane spell")
    :Tooltip("§7Right-click to learn Meteor Strike")
    :OnRightClick(function(player, itemStack)
        player:getAttribute("spell_tome_used")
        player:setAttribute("spell_tome_used", "true")
        player:sendActionBar("§dYou have learned §lMeteor Strike§r§d!")
        player:playSound("minecraft:entity.player.levelup", 1.0, 0.5)
    end)
    :Register()

-- ==== BLOCKS ====

local CrystalOre = Content.NewBlock("crystal_ore")
    :Hardness(4.0)
    :Resistance(12.0)
    :LightLevel(5)
    :SoundType("STONE")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("iron")
    :Drop("luatweaker:crystal_shard", 2, 5)
    :DropExperience(5, 12)
    :CreativeTab("arcane_tab")
    :Tag("c:ores/crystal")
    :Register()

local CrystalBlock = Content.NewBlock("crystal_block")
    :Hardness(5.0)
    :Resistance(20.0)
    :LightLevel(10)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("diamond")
    :MapColor("DIAMOND")
    :PushReaction("BLOCK")
    :RedstoneConductor(false)
    :CreativeTab("arcane_tab")
    :Register()

local CrystalAltar = Content.NewBlock("crystal_altar")
    :Hardness(3.0)
    :Resistance(10.0)
    :LightLevel(8)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("iron")
    :MapColor("PURPLE")
    :DisplayName("Crystal Altar")
    :CreativeTab("arcane_tab")
    :Container(3, 9, "spill")
    :ContainerTitle("Crystal Altar")
    :OnRightClick(function(player, blockState)
        player:sendActionBar("§bThe altar hums with arcane power...")
        return true
    end)
    :Register()

-- ==== ENTITY: CRYSTAL GOLEM BOSS ====
Content.createEntity("crystal_golem", function(entity)
    entity:category("MONSTER")
          :parent("iron_golem")
          :dimensions(1.4, 2.8)
          :maxHealth(500)
          :movementSpeed(0.3)
          :attackDamage(12.0)
          :followRange(40.0)
          :armor(10.0)
          :knockbackResistance(0.8)
          :spawnEgg(0x4488FF, 0x88CCFF)
          :texture("luatweaker:textures/entity/crystal_golem.png")
          :ambientSound("minecraft:entity.iron_golem.step")
          :hurtSound("minecraft:entity.iron_golem.hurt")
          :deathSound("minecraft:entity.iron_golem.death")
          :drop("luatweaker:crystal_shard", 10, 20)
          :drop("luatweaker:crystal_staff", 1, 1)
          :experience(200)
          :bossBar("§b§lCrystal Golem", "BLUE", "PROGRESS")
          :creativeTab("arcane_tab")
end)

-- ==== ENTITY: CRYSTAL BEAST (native quadruped, forest dweller) ====
Content.createEntity("crystal_beast", function(entity)
    entity:category("MONSTER")
          :parent("cow")
          :dimensions(0.9, 1.4)
          :maxHealth(40)
          :movementSpeed(0.25)
          :attackDamage(5.0)
          :followRange(24.0)
          :spawnEgg(0x46C9A0, 0xBDFFD9)
          :texture("luatweaker:textures/entity/crystal_beast.png")
          :hurtSound("minecraft:entity.cow.hurt")
          :deathSound("minecraft:entity.cow.death")
          :drop("luatweaker:crystal_shard", 2, 5)
          :experience(12)
          :creativeTab("arcane_tab")
end)

-- ==== ENTITY: CRYSTAL CREEPER (native, wastes dweller) ====
Content.createEntity("crystal_creeper", function(entity)
    entity:category("MONSTER")
          :parent("creeper")
          :dimensions(0.6, 1.7)
          :maxHealth(25)
          :movementSpeed(0.3)
          :followRange(24.0)
          :spawnEgg(0x78DC5A, 0xDEFFC8)
          :texture("luatweaker:textures/entity/crystal_creeper.png")
          :hurtSound("minecraft:entity.creeper.hurt")
          :deathSound("minecraft:entity.creeper.death")
          :drop("luatweaker:crystal_shard", 1, 3)
          :experience(8)
          :creativeTab("arcane_tab")
end)

-- Register custom projectile for Crystal Bolt skill
Content.registerProjectile("crystal_bolt", {
    damage = 8.0,
    explosionPower = 0,
    trailParticle = "minecraft:end_rod"
})

print("[ArcaneRPG] Content registered: 10 items, 3 blocks, 1 boss entity, 1 creative tab")
