-- ===================================================================
-- LuaTweaker Custom Content: Full Ruby Gear, Tools, Armor & Models
-- ===================================================================
local Content = require("LuaTweaker.Content")

-- 0. Explicit Custom Creative Tabs
Content.createTab("ruby_tab", function(tab)
    tab:title("Ruby Treasures")
       :icon("luatweaker:custom_ruby")
end)

Content.createTab("magic_tab", function(tab)
    tab:title("Arcane Treasures")
       :icon("luatweaker:magic_staff")
end)

-- 1. Ruby Gem Item & Enchanted Ruby Apple (Food & Consumable)
local CustomRuby = Content.NewItem("custom_ruby")
    :MaxStackSize(64)
    :Rarity("EPIC")
    :BurnTime(400)
    :DisplayName("Enchanted Ruby Gem")
    :CreativeTab("ruby_tab")
    :Tag("c:gems/ruby")
    :Tag("c:gems")
    :OnRightClick(function(player, itemStack)
        player:sendActionBar("§6Enchanted Ruby Gem shines bright!")
        player:playSound("luatweaker:ruby_equip", 1.0, 1.2)
    end)
    :Register()

local RubyApple = Content.NewItem("ruby_apple")
    :DisplayName("Enchanted Ruby Apple")
    :Rarity("EPIC")
    :Glow(true)
    :Tooltip("§dHồi phục sinh lực tức thì & Kháng cự gia tăng")
    :Food(6, 1.2)
    :AlwaysEdible()
    :CreativeTab("ruby_tab")
    :OnConsume(function(player, stack)
        player:sendActionBar("§dYou feel radiant Ruby magic surging through you!")
        player:addEffect("regeneration", 200, 1)
        player:addEffect("resistance", 6000, 0)
        player:playSound("minecraft:entity.player.burp", 1.0, 1.0)
    end)
    :Register()

-- 2. Ruby Blocks (kèm Inline Block Drops & EXP Drops)
local RubyOre = Content.NewBlock("ruby_ore")
    :Hardness(4.5)
    :Resistance(15.0)
    :LightLevel(3)
    :SoundType("STONE")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("iron")
    :Drop("luatweaker:raw_ruby", 1, 2)
    :DropExperience(3, 7)
    :CreativeTab("ruby_tab")
    :Tag("c:ores/ruby")
    :Tag("c:ores")
    :Register()

local DeepslateRubyOre = Content.NewBlock("deepslate_ruby_ore")
    :Hardness(6.0)
    :Resistance(18.0)
    :LightLevel(3)
    :SoundType("DEEPSLATE")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("iron")
    :Drop("luatweaker:raw_ruby", 1, 3)
    :DropExperience(4, 9)
    :CreativeTab("ruby_tab")
    :Tag("c:ores/ruby")
    :Tag("c:ores")
    :Register()

local RubyBlock = Content.NewBlock("ruby_block")
    :Hardness(5.0)
    :Resistance(30.0)
    :LightLevel(8)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :MiningLevel("iron")
    :CreativeTab("ruby_tab")
    :Tag("c:storage_blocks/ruby")
    :Tag("c:storage_blocks")
    :Register()

local RubySlab = Content.NewBlock("ruby_slab")
    :Hardness(5.0)
    :Resistance(30.0)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :CreativeTab("ruby_tab")
    :Register()

local RubyStairs = Content.NewBlock("ruby_stairs")
    :Hardness(5.0)
    :Resistance(30.0)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :CreativeTab("ruby_tab")
    :Register()

local RubyWall = Content.NewBlock("ruby_wall")
    :Hardness(5.0)
    :Resistance(30.0)
    :SoundType("METAL")
    :RequiresTool(true)
    :MineableWith("pickaxe")
    :CreativeTab("ruby_tab")
    :Register()

local WoodCrate = Content.NewBlock("wood_crate")
    :Hardness(2.0)
    :Resistance(5.0)
    :SoundType("WOOD")
    :MineableWith("axe")
    :Drop("luatweaker:wood_crate", 1, 1)
    :CreativeTab("ruby_tab")
    :OnRightClick(function(player, blockState)
        player:sendMessage("§e[Storage Crate] Capacity: 27 Slots")
        player:playSound("minecraft:block.chest.open", 1.0, 1.0)
    end)
    :Register()

-- 3. Dynamic KeyMapping Registration (Controls Menu)
Content.NewKeyMapping("staff_swap_skill")
    :DisplayName("Staff Skill Swap")
    :Category("luatweaker")
    :DefaultKey(90)
    :OnPress("StaffSwapSkill")
    :Register()

-- 4. Raw Ruby Gem Item
local RawRuby = Content.NewItem("raw_ruby")
    :MaxStackSize(64)
    :Rarity("RARE")
    :DisplayName("Raw Ruby")
    :CreativeTab("ruby_tab")
    :Tag("c:raw_materials/ruby")
    :Register()

-- 4. Full Ruby Tool Set
local RubySword = Content.NewItem("ruby_sword")
    :Type("sword")
    :DisplayName("Ruby Sword")
    :AttackDamage(8.5)
    :AttackSpeed(-2.4)
    :Durability(1800)
    :CreativeTab("ruby_tab")
    :OnHitEntity(function(targetEntity, shooterPlayer)
        targetEntity:addEffect("minecraft:slowness", 100, 1)
        shooterPlayer:playSound("minecraft:entity.player.attack.crit", 1.0, 1.2)
    end)
    :Register()

local RubyPickaxe = Content.NewItem("ruby_pickaxe")
    :Type("pickaxe")
    :DisplayName("Ruby Pickaxe")
    :AttackDamage(7.0)
    :AttackSpeed(-2.8)
    :MiningSpeed(9.0)
    :MiningLevel("netherite")
    :Durability(1800)
    :CreativeTab("ruby_tab")
    :Register()

local RubyAxe = Content.NewItem("ruby_axe")
    :Type("axe")
    :DisplayName("Ruby Axe")
    :AttackDamage(10.0)
    :AttackSpeed(-3.0)
    :MiningSpeed(9.0)
    :Durability(1800)
    :CreativeTab("ruby_tab")
    :Register()

local RubyShovel = Content.NewItem("ruby_shovel")
    :Type("shovel")
    :DisplayName("Ruby Shovel")
    :AttackDamage(6.5)
    :AttackSpeed(-3.0)
    :MiningSpeed(9.0)
    :Durability(1800)
    :CreativeTab("ruby_tab")
    :Register()

local RubyHoe = Content.NewItem("ruby_hoe")
    :Type("hoe")
    :DisplayName("Ruby Hoe")
    :AttackDamage(2.0)
    :AttackSpeed(0.0)
    :Durability(1800)
    :CreativeTab("ruby_tab")
    :Register()

-- 5. Full Ruby Armor Set
Content.createArmorMaterial("ruby", function(mat)
    mat:layer("luatweaker:ruby")
       :equipSound("luatweaker:ruby_equip")
       :toughness(3.0)
       :knockbackResistance(0.1)
       :enchantability(20)
       :defense("helmet", 4)
       :defense("chestplate", 9)
       :defense("leggings", 7)
       :defense("boots", 4)
end)

local RubyHelmet = Content.NewItem("ruby_helmet")
    :Type("helmet")
    :DisplayName("Ruby Helmet")
    :ArmorMaterial("ruby")
    :ArmorTexture("luatweaker:ruby")
    :Durability(500)
    :CreativeTab("ruby_tab")
    :Register()

local RubyChestplate = Content.NewItem("ruby_chestplate")
    :Type("chestplate")
    :DisplayName("Ruby Chestplate")
    :ArmorMaterial("ruby")
    :ArmorTexture("luatweaker:ruby")
    :Durability(700)
    :CreativeTab("ruby_tab")
    :Register()

local RubyLeggings = Content.NewItem("ruby_leggings")
    :Type("leggings")
    :DisplayName("Ruby Leggings")
    :ArmorMaterial("ruby")
    :ArmorTexture("luatweaker:ruby")
    :Durability(650)
    :CreativeTab("ruby_tab")
    :Register()

local RubyBoots = Content.NewItem("ruby_boots")
    :Type("boots")
    :DisplayName("Ruby Boots")
    :ArmorMaterial("ruby")
    :ArmorTexture("luatweaker:ruby")
    :Durability(550)
    :CreativeTab("ruby_tab")
    :Register()

-- 5. Molten Ruby Liquid Fluid
local RubyFluid = Content.NewFluid("ruby_fluid")
    :DisplayName("Molten Ruby Liquid")
    :StillTexture("luatweaker:block/ruby_fluid_still")
    :FlowingTexture("luatweaker:block/ruby_fluid_flow")
    :Color(0xFFE60033)
    :Luminance(10)
    :Density(3000)
    :Viscosity(6000)
    :CreativeTab("ruby_tab")
    :Register()

-- 6. Magic Ranged Staff
Content.registerProjectile("luatweaker:ruby_orb", { damage = 25, explosionPower = 2, trailParticle = "minecraft:flame" })

-- 6b. Ruby Overseer Boss Entity (spawned by the Magic Staff 'Summon Ruby Guardian' skill)
Content.createEntity("ruby_boss", function(entity)
    entity:parentMob("zombie")
    entity:maxHealth(300)
    entity:dimensions(0.9, 2.5)
    entity:movementSpeed(0.35)
    entity:attackDamage(8.0)
    entity:followRange(32)
    entity:armor(6.0)
    entity:creativeTab("ruby_tab")
end)

local MagicStaff = Content.NewItem("magic_staff")
    :Type("ranged")
    :DisplayName("§bStaff of Arcane Elements")
    :AttackDamage(6.0)
    :AttackSpeed(-2.0)
    :Rarity("EPIC")
    :Glow(true)
    :CreativeTab("magic_tab")
    :OnRightClick(function(player, itemStack)
        local Events = require("LuaTweaker.Events")
        if Events then
            Events:Fire("MagicStaffUsed", { player = player, itemStack = itemStack })
        end
    end)
    :Register()

-- 7. KeyBindings for Magic Staff Controls (Cast: 'G' key, Switch: 'R' key)
Content.NewKeyMapping("magic_staff_cast")
    :displayName("Magic Staff: Cast Selected Skill")
    :category("LuaTweaker Controls")
    :defaultKey(71)
    :onPress("StaffCastSkill")
    :register()

Content.NewKeyMapping("magic_staff_switch")
    :displayName("Magic Staff: Switch Active Skill")
    :category("LuaTweaker Controls")
    :defaultKey(82)
    :onPress("StaffSwapSkill")
    :register()

-- 8. KeyBinding: Mark Target (X) — raycast the entity in front, draw a client-only outline
local markCfg = mod and mod:GetConfig() or {}
Content.NewKeyMapping("magic_staff_mark_target")
    :displayName("Magic Staff: Mark Target")
    :category("LuaTweaker Controls")
    :defaultKey(markCfg.mark_target_key or 88)
    :onPress("TargetMark")
    :register()
