package com.luatweaker.core.lsp;

import com.luatweaker.api.annotation.LuaDoc;
import com.luatweaker.api.objects.IItem;
import com.luatweaker.api.wrapper.IngredientWrapper;

import java.lang.reflect.Method;
import java.util.*;
import java.util.stream.Collectors;

public class LtvmStubGenerator {
    private final Map<String, Class<?>> registeredServices = new LinkedHashMap<>();
    private final Set<Class<?>> processedClasses = new HashSet<>();
    private final StringBuilder classStubs = new StringBuilder();

    public LtvmStubGenerator() {
        // Automatically generate stubs for core API objects
        generateClassStub(IItem.class, "IItem");
        generateClassStub(IngredientWrapper.class, "IngredientWrapper");
    }

    /**
     * Registers a script service and dynamically generates its LSP stub.
     *
     * @param serviceName      The name used in Mod:GetService(serviceName)
     * @param serviceInterface The Java interface or class representing the service
     * @return This generator instance for chaining
     */
    public LtvmStubGenerator registerService(String serviceName, Class<?> serviceInterface) {
        registeredServices.put(serviceName, serviceInterface);
        generateClassStub(serviceInterface, serviceName);
        return this;
    }

    public void generateClassStub(Class<?> clazz, String luaClassName) {
        if (clazz == null || processedClasses.contains(clazz)) {
            return;
        }
        processedClasses.add(clazz);

        LuaDoc typeDoc = clazz.getAnnotation(LuaDoc.class);
        if (typeDoc != null && !typeDoc.description().isEmpty()) {
            classStubs.append("--- ").append(typeDoc.description()).append("\n");
        }
        classStubs.append("---@class ").append(luaClassName).append("\n");
        classStubs.append("local ").append(luaClassName).append(" = {}\n\n");

        for (Method method : clazz.getDeclaredMethods()) {
            LuaDoc doc = method.getAnnotation(LuaDoc.class);
            if (doc != null) {
                if (!doc.description().isEmpty()) {
                    classStubs.append("--- ").append(doc.description()).append("\n");
                }
                for (String param : doc.params()) {
                    classStubs.append("---@param ").append(param).append("\n");
                }
                if (!"void".equalsIgnoreCase(doc.returnType())) {
                    classStubs.append("---@return ").append(doc.returnType()).append("\n");
                }

                classStubs.append("function ").append(luaClassName).append(":")
                    .append(method.getName()).append("(");

                String[] params = doc.params();
                for (int i = 0; i < params.length; i++) {
                    String p = params[i];
                    int colonIndex = p.indexOf(':');
                    String pName = colonIndex != -1 ? p.substring(0, colonIndex).trim() : p.trim();
                    classStubs.append(pName);
                    if (i < params.length - 1) {
                        classStubs.append(", ");
                    }
                }

                classStubs.append(") end\n\n");
            }

            // Transitive scanning: check if return type has @LuaDoc
            Class<?> returnType = method.getReturnType();
            if (returnType.isAnnotationPresent(LuaDoc.class) && !processedClasses.contains(returnType)) {
                generateClassStub(returnType, returnType.getSimpleName());
            }
            // Transitive scanning: check if parameter types have @LuaDoc
            for (Class<?> paramType : method.getParameterTypes()) {
                if (paramType.isAnnotationPresent(LuaDoc.class) && !processedClasses.contains(paramType)) {
                    generateClassStub(paramType, paramType.getSimpleName());
                }
            }
        }
    }

    public String getResult() {
        StringBuilder stub = new StringBuilder("---@meta\n-- Auto-generated by LTVM Engine\n\n");

        // Dynamic Service Resolution Union Types
        stub.append("--- Global Mod service manager\n");
        stub.append("---@class Mod\n");
        stub.append("Mod = {}\n\n");

        if (registeredServices.isEmpty()) {
            stub.append("--- Resolves a registered service.\n");
            stub.append("---@param name string\n");
            stub.append("---@return any\n");
            stub.append("function Mod:GetService(name) end\n\n");
        } else {
            String paramUnion = registeredServices.keySet().stream()
                .map(s -> "'" + s + "'")
                .collect(Collectors.joining(" | "));
            String returnUnion = String.join(" | ", registeredServices.keySet());

            stub.append("--- Resolves a registered service.\n");
            stub.append("---@param name ").append(paramUnion).append("\n");
            stub.append("---@return ").append(returnUnion).append("\n");
            stub.append("function Mod:GetService(name) end\n\n");
        }

        stub.append("--- Global game service manager (alias for Mod)\n");
        stub.append("---@class game : Mod\n");
        stub.append("game = {}\n\n");

        stub.append("--- Creates an abstract item wrapper.\n");
        stub.append("---@param itemId string The Registry ID of the item.\n");
        stub.append("---@param count number? The count of the item stack (defaults to 1).\n");
        stub.append("---@return IItem\n");
        stub.append("function item(itemId, count) end\n\n");

        stub.append("--- Creates an ingredient wrapper.\n");
        stub.append("---@param descriptor string The registry ID or tag (prefixed with #).\n");
        stub.append("---@return IngredientWrapper\n");
        stub.append("function ingredient(descriptor) end\n\n");

        // Append all collected class stubs
        stub.append(classStubs);

        return stub.toString();
    }
}

