plugins {
    id 'java-library'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

dependencies {
    api project(':common-api')
    api 'cc.tweaked:cobalt:0.9.9'
    
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
    from {
        configurations.runtimeClasspath.filter { it.name.contains('cobalt') }.collect { zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}
